# Generated by Django 5.1.3 on 2025-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_class',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
    ]
