# Generated by Django 5.1.3 on 2024-11-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_graduatingstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraduatingStudents',
        ),
    ]
