# Generated by Django 5.1.3 on 2024-11-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newscategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='Category',
        ),
    ]
