# Generated by Django 5.1.3 on 2025-04-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduatingstudents',
            options={'ordering': ['-graduation_date', 'name'], 'verbose_name': 'Mezun Öğrenci', 'verbose_name_plural': 'Mezun Öğrenciler'},
        ),
        migrations.AddField(
            model_name='graduatingstudents',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv_files', verbose_name='CV Dosyası'),
        ),
        migrations.AddField(
            model_name='graduatingstudents',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='graduatingstudents',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='graduatingstudents',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='graduatingstudents',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='graduatingstudents',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graduates.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='graduation_date',
            field=models.DateField(verbose_name='Mezuniyet Tarihi'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='img',
            field=models.ImageField(upload_to='graduates', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='graduatingstudents',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Soyadı'),
        ),
    ]
