# Generated by Django 5.1.3 on 2024-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_title', models.CharField(max_length=50)),
                ('projects_description', models.CharField(max_length=250)),
                ('projects_topic', models.CharField(max_length=250)),
            ],
        ),
    ]
