# Generated by Django 5.1.3 on 2024-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstudents',
            name='projects_class',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='projectstudents',
            name='projects_last_date',
            field=models.DateField(null=True),
        ),
    ]
