# Generated by Django 5.1.3 on 2024-12-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0003_alter_projectstudents_projects_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstudents',
            name='projects_class',
            field=models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4'), (5, 'Class 5')]),
        ),
    ]
