# Generated by Django 5.1.3 on 2024-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0004_alter_projectstudents_projects_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstudents',
            name='projects_topic',
        ),
        migrations.AlterField(
            model_name='projectstudents',
            name='projects_class',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 'G')]),
        ),
    ]
