# Generated by Django 5.1.3 on 2024-12-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0008_projectrequest_projects_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_class',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_deadline',
        ),
    ]
