# Generated by Django 5.1.3 on 2025-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0009_remove_studentsubmission_submission_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='projects_class',
            field=models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4')], null=True),
        ),
    ]
