# Generated by Django 5.1.3 on 2025-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0010_alter_projectrequest_projects_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='submission_description',
            new_name='submission_description_1',
        ),
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='submission_title',
            new_name='submission_title_1',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_description_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_description_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_title_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_title_3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
