# Generated by Django 5.1.3 on 2025-01-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0011_rename_submission_description_studentsubmission_submission_description_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='submission_description_1',
            new_name='submission_description',
        ),
        migrations.RenameField(
            model_name='studentsubmission',
            old_name='submission_title_1',
            new_name='submission_title',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_description_2',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_description_3',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_title_2',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_title_3',
        ),
    ]
