# Generated by Django 5.1.3 on 2025-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0012_rename_submission_description_1_studentsubmission_submission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='is_approved',
            field=models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Not Approved')], default=0),
        ),
    ]
