# Generated by Django 5.1.3 on 2025-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0019_alter_projectrequest_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='submision_start',
            field=models.DateTimeField(null=True),
        ),
    ]
