# Generated by Django 5.1.3 on 2025-02-20 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0020_projectrequest_submision_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='submision_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 0), null=True),
        ),
    ]
