# Generated by Django 5.1.3 on 2025-02-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0022_rename_submision_start_projectrequest_submission_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_link', models.URLField()),
                ('week_number', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('submission_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_submissions', to='student_projects.studentsubmission')),
            ],
        ),
    ]
