# Generated by Django 5.1.3 on 2025-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_projects', '0023_weeksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeksubmission',
            name='is_approved',
            field=models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Not Approved')], default=2),
        ),
    ]
